### ISSUE TITLE
_installer\index\mysql.php nicht E_Strict (Notice!)

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#10]
Hallo habe da noch eine kleine sache gefunden die du noc verbessern koenntest in der datei _installer\index\mysql.php.

Zeile 19:
$msg=''; $nextlink=''; $dbe_selected0 = ''; $dbe_selected1 = ''; $dbe_selected2 = ''; $dbe_selected3 = '';  $disabled = '';
mit:
$msg=''; $nextlink=''; $dbe_selected0 = ''; $dbe_selected1 = ''; $dbe_selected2 = ''; $dbe_selected3 = ''; $dbe_selected4 = ''; $disabled = '';
ersetzen um somit die Notice weg zubekommen

![installer_mysql error](https://f.cloud.github.com/assets/5182697/926106/42d1f230-ff85-11e2-920e-04ec12d937be.jpg)

**Comment by hammermaps** [comment]
Deine Kopie aktuell?
Die Zeile steht schon im Code.^^

**Comment by Aviator-Coding** [comment]
wie gesagt vor 2 tagen ausgecheckt

**Comment by hammermaps** [comment]
Ich denke kann zu^^
