### ISSUE TITLE
Installation MYSQL Passwort

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#11]
Momentan ist es so das wenn du kein Mysql Passwort eingibst und doch auch keins hast laesst er sich eine verbindung aufbauen und sobald du auf weiter klickst bekommste ne Fehlermeldung das kein Passwort eingetragen wurde in der /inc/mysql.php. Solltest dann doch vorher nochmal nen !empty() machen das man bei der verbindung nicht weiter kommt ansonsten bekommste das hier,

![installer_empty_pw](https://f.cloud.github.com/assets/5182697/926185/bd4cd916-ff86-11e2-993a-9085018694f5.jpg)

**Comment by hammermaps** [comment]
Normalfall ist ein Passwort vorhanden, aber könnte man machen.
Kannst es gerne ändern und einen Issue dazu machen.
Andernfals bau ich das mit dem nächsten größeren commit ein.

**Comment by hammermaps** [comment]
Ist mit im Update #15 vom 08.08.2013.
