### ISSUE TITLE
/news/index.php

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#12]
Als erstes setzt du das Error Handling in den ersten Zeilen 8&9 und dann includest du die bbcode und ueberschreibst es. (Ist mehr nen schoenheits fehler)

ini_set('display_errors', 1);
error_reporting(E_ALL);

fliegt raus aus der Datei

**Comment by hammermaps** [comment]
Versteh ich nicht?
Eine bbcode gibt es nicht mehr.
Deine Zeilen beziehen sich auf die emalige bbcode.php?

**Comment by Aviator-Coding** [comment]
du hattest das in der news datei stehen. Du setzt das error handling 2 mal

**Comment by hammermaps** [comment]
Kann sein das es mal so drine stand, dann aber aus testgründen.
Im Moment sollte es nur 2 mal in der common.php stehen, 
einmal als standard, dann einmal in einer if() anweisung für alle fehler/notices anzeigen. _Debug_
Die in der if anweisung überschreibt den standard wenn debug => true ist.
