### ISSUE TITLE
/votes/pages/action_default.php

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#13]
There are 3 Issues in that file.

Ich wuerde line 
76:
if(($_GET['action'] == "show" && $get['id'] == $_GET['id']) || isset($_GET['show']) && $get['id'] == $_GET['show'])

gegen 
    if(($IncludeAction['do'] == "show" && $get['id'] == $_GET['id']) || isset($_GET['show']) && $get['id'] == $_GET['show'])

tauschen.

wuerde in Zeile 36:
 else {
            $ipcheck = false;
            $intern = '';
        } 
gegen
     else
        {
            $ipcheck = false;
            $intern = '';
            $showVoted = '';
        }
tauschen

und in Zeile 104 

"menu" => $menu,

komplett raus loeschen wird gar nicht benutzt in der template datei

![votes](https://f.cloud.github.com/assets/5182697/926453/805355a8-ff8b-11e2-867e-b875eb45d54a.jpg)

**Comment by hammermaps** [comment]
Hallo, Aviator.
Viele der Seiten sind noch teils im DZCP uhrsprung und müssen überabreitet werden.
Hast du eine aktuelle version gezogen? 
Denn die Codezeilen gibt es nicht mehr^^
Aber danke für deine Hilfe, ich werde gerne deine Ideen und Anmerkungen einfließen lassen.
