### ISSUE TITLE
XML dateien im Admin Menu

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#14]
Was mir mal aufgefallen ist das du die xml dateien wenn du den pfad weisst auch extern aufmachen kannst wuerde ich durch eine .htaccess verweigern. Nicht das dadurch ien sicherheitsloch entsteht

**Comment by hammermaps** [comment]
Besser ist das, aber ansich steht in den xml files nichts drine was wirklich kritisch ist, sind halt nur einstellungen.

**Comment by Aviator-Coding** [comment]
wuerde es trotzdem machen
