### ISSUE TITLE
Fehler im Installer

### ISSUE THREAD

**Issue by Der-WU** [Hammermaps-DEV/DZCP-Extended-Edition#2]
Hallo.

Ich habe durch zufall die DZCP EE entdeckt und wollt sie gleich mal testen.
Also hoch geladen und installation starten wollen und zack, direkt der erste Fehler. :(

Parse error: syntax error, unexpected '[' in /var/www/Privat/htdocs/2013/inc/database.php on line 38

Woran kann das liegen? 

Danke & Gruß WU

**Comment by hammermaps** [comment]
Schau ich mir an^^

Kann sein das ich die Syntax von PHP 5.4 verwendet habe, die mag 5.3 nicht so ganz^^

**Comment by hammermaps** [comment]
Kannst du bitte nochmal eine aktuelle kopie runterladen und versuchen.
Wenn das wieder kommt, würde ich gerne mal in die Datei reinschauen die den Fehler verursacht..

Gruß, zurück^^

**Comment by hammermaps** [comment]
Ok, hab es auf funpic getestet, noch was gefunden.
Lade dir hier die Version neu runter, sollte gehen.

Handelt sich aber nur um eine unfertige Version^^

**Comment by Der-WU** [comment]
Okay der Fehler ist behoben. Aber es geht weiter:

Warning: ftp_site(): /htdocs/2013//inc/_cache: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/_cache/binary: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/_cache/tinymce: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/images/uploads/useravatare: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/images/uploads/usergallery: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/images/uploads/news: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343 Warning: ftp_site(): /htdocs/2013//inc/tinymce_files: Datei oder Verzeichnis nicht gefunden in /var/www/Privat/htdocs/2013/_installer/system/core.php on line 343

Kann auch nicht funktionieren da die Ordner gar nicht existieren. :)

Gruß WU

**Comment by hammermaps** [comment]
Hast die Rechte automatisch setzen lassen, das hat noch par macken, ist aber im Moment eher unwichtig da es sich um keine kritische sache handelt^^ 
Das kommt wenn das wichtigeste richtig leuft, die ordner sollen aber in dem github zip download dine sein und auf deinem ftp vorhanden, fehlen nur die schreib und lese Rechte.
Da musst du das noch Manuell machen, viele machen wieso schreibreche auf den ganzen Ordner, was eigendlich nicht so toll ist.
Mache das aber selber^^ Bin zu faul die Daten/Ordner einzelnd zu bearbeiten xD

**Comment by hammermaps** [comment]
Ok.. Ordner fehlen :( , Github hats kaputt gemacht^^

Edit:
Hab NULL Files eingefügt damit Github die Ordner erkennt, fehlten par mehr^^ 
Lade dir das nochmal oder schau hier welche ordner fehlten: https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/b5cfdf2191c0a115e5a7f5490826cd33cbabb4e8
https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/53a08ae7fb30d2edc4cefe63edac2276cbdfe668

**Comment by Der-WU** [comment]
Mein Webserver passt Ordner rechte von alleine an. :) ich hab nur gedacht ich sag bescheid bevor das später los geht. :)  ich muss mich mal einlesen. Dann pull ich kleine fixes selber. Dann hast du ein bischen weniger Arbeit. :)

**Comment by hammermaps** [comment]
Das ist super von dir, das du helfen möchtest, dem bin ich nicht abgeneigt^^
Kleine fehler schleichen sich immer ein^^, da kannst du immer helfen wenn du lust hast.
Hoffe das sonst das meiste rundleuft und keine größeren Probleme macht.
Würde mich interessieren wenn du es zum laufen bekommst, ob du mir die Support Informationen zukommen lassen könntest, Interessant für mich sind die Abschnitte: Server Versionen, Cache Support und Servereinstellungen.
(Reine Statistik^^)

**Comment by Der-WU** [comment]
Jetzt verlief die Installation reibungslos.

Hier die Support Infos:

#####################
Support Informationen
#####################

#####################
DZCP Allgemein 
#####################
DZCP Version: 1.0
DZCP Release: 10.07.2013
DZCP Build: repo:dev:git:0170
DZCP Edition: Extended Edition

#####################
DZCP Erweiterungen 
#####################
GameQ: 2.0.1

#####################
Domain & User
#####################
Domain: http://der-wu.de/2013/
System/Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.72 Safari/537.36

#####################
Server Versionen
#####################
Server OS: Linux titan787.server4you.de 2.6.32-5-amd64 #1 SMP Sun Sep 23 10:07:46 UTC 2012 x86_64
Webserver: PHP läuft als CGI <Keine Info>
PHP-Version: 5.3.3-7+squeeze15 (CGI)
MySQL-Server Version: 5.1.66-0+squeeze1
MySQL-Erweiterung: MySQLi
MySQL-Client Version: 5.1.66
Zend-Engine: 2.3.0

#####################
Socket-Verbindungen 
#####################
PHP fsockopen: Aktiviert
PHP allow_url_fopen: Aktiviert
PHP Sockets: Aktiviert

#####################
Cache Support 
#####################
ZEND Server - Disk Cache Erweiterung: Deaktiviert
ZEND Server - Disk Cache: Deaktiviert
MySQL Cache Erweiterung: Ist verfügbar
MySQL Cache: Ist verfügbar
File Cache: Ist verfügbar
ZEND Server - Shared Memory Cache Erweiterung: Deaktiviert
ZEND Server - Shared Memory Cache: Deaktiviert
Memcache Erweiterung: Deaktiviert
Memcache: Deaktiviert
Aktuell verwendet: File Cache

#####################
Servereinstellungen
#####################
register_globals: Off
Save Mode: Off
open_basedir: /var/www/Privat/htdocs:/var/www/Privat/apps:/var/www/Privat/priv:/var/www/Privat/tmp:/usr/share/pear:/usr/share/php:/tmp
GD-Version: 2.0
PHP-Memory Limit: 64M
Imagick Erweiterung: Aktiviert
Verwendet Imagick: Ja
imagettftext(): existiert
HTTP_ACCEPT_ENCODING: gzip,deflate,sdch
magic_quotes_gpc: On
file_uploads: On
upload_max_filesize: 50M
sendmail_from: no value
sendmail_path: /usr/sbin/sendmail -t -i 

Intensiv testen kann ich leider nicht, da ich DZCP als Private Homepage verwende.
Also auf die meisten Clan Funktionen verzichte ich. :) 
Was mir aber gleich auffällt ist das der TS Viewer den TS Server nicht läd.
Geändert habe ich ihn bereits ^^

**Comment by hammermaps** [comment]
Danke für die Infos^^

Das mit dem Intensiv testen machen später die DZCP.de Moderatoren ich kenne die meisten, die helfen gerne beim testen wenn es so weit ist^^
Was TS und Gameserver angeht, das dauert bei dir schon lange.
Was das Template angeht, da werden viele Texte fehlen und die Javaskripte sind auch stark verändert.
Man braucht spizell angepasste Templates, die für die Version geschrieben sind, oder man baut es sich selber um. ^^

Hier ist meine Testversion, da kannst du ggf. schauen wenn etwas bei dir nicht geht.
http://www.hammermaps.de/news/

**Comment by Der-WU** [comment]
Bin gerade dabei es mir umzubauen. ;) 
Gibt es die Möglichkeit GameQ zu Debuggen um herauszufinden wieso er keine Daten vom TS3 und GS Server bekommt?

**Comment by hammermaps** [comment]
GameQ kann man debuggen aber es ist sehr umständlich, ich arbeite grade dran, das in die debug console zu bekommen.

**Comment by Der-WU** [comment]
Kein stress.
Liegt wieder an der PHP Version.
Hab mir eine andere buffer.PHP von gameq besorgt.
Damit geht es Fehler frei.

https://github.com/Austinb/GameQ

Gruß WU

**Comment by hammermaps** [comment]
hmm, ok gibt warscheinlich bugs und kleine probleme wenn die php version älter ist als PHP 5.4
Ich hab die Version nur auf aktuellen php 5.4 servern laufen.^^

Edit:
Ok, hab PHP 5.4 Syntax in der buffer.php gefunden, das kann auf 5.3 nicht laufen.
Ich ändere es, das es richtig auf 5.3 geht, kommt dann mit dem nächsten update.
Wenn du die Datei jetzt schon brauchst, dann sag bescheid ich lade die dann schon hoch.

Edit 2:
Ich hab davon noch mehr gefunden bei fast allen BF Games und allen Source (Half-Life, CSS, etc)
Ich habe hier https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/e429be0da457aec4c0345fd483412944a18c8fbf die korektur hochgeladen, oder lad dir neue zip datei von hier und überschreibe nur den inc/gameq ordner, danach solltes es gehen^^

**Comment by Der-WU** [comment]
SO. Hab dann mal das Template zu 90 % angepasst.
Hab noch nen 2 Fehler gefunden die wohl auf PHP 5.4 zurück zu führen sind.
1. Die Comment Funktion funktioniert nicht:
   Fatal error: Call to undefined function bbcode() in /var/www/Privat/htdocs/2013/gb/pages/action_admin.php on line 78
2. Die Umfragen werden auf der Übersichtsseite nicht angezeigt:
   "WARNUNG: MySQL Query"
   "Fail MySQL Query: SELECT \* FROM dzcp_votes AND forum = 0 ORDER BY intern DESC, datum DESC"
   "WARNUNG:' /inc/database.php '"
   "Line:"368" => mysqli_fetch_assoc(): Couldn't fetch mysqli_result"

Desweiteren hab ich nen Feature Wunsch.
Wäre cool wenn Events nicht nur einen Start haben sondern auch eine Ende, so das man ein Event z.b über eine Woche im Kalender anzeigen lassen kann ohne für jeden Tag ein zu schreiben. :)

Gruß WU

EDIT1:
Teamspeak Anzeige -> Leere Channel nicht anzeigen greift nicht.
Adminbereich -> Default Sprache wird nicht gespeichert.
Adminbereich -> Kein Standart Template auswählbar.

Gruß WU

**Comment by hammermaps** [comment]
Danke für das Feedback und die gefunden fehler, werde die aus der welt schaffen^^
Schreibe bitte dein Feature Wunsch in einen neuen issue, da ich das erst mache wenn ich bei der überarbeitung des Kalenders ankomme.

Teamspeak Anzeige ist mir auch gestern aufgefallen^^ *Ist schon behoben. (Hab aber noch nicht Hochgeladen)
Die anderen 2 Punke im Adminbereich schaue ich mir nochmal an.

**Comment by hammermaps** [comment]
Hab das Update oben, Ich hab dir eine ZIP Datei gemacht brauchst du nur alles zu überschreiben.
https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/tree/master/_updates_zip_

**Comment by Der-WU** [comment]
Okay.
Teamspeak werden leere Channels nun ausgeblendet.
Auch im Adminbereich kann man nun Sprache und Template wählen. :)

Bleibt nur noch der Fehler bei der Umfragen Übersicht. 

Gruß WU

**Comment by hammermaps** [comment]
Wo, soll das mit der Umfragenübersicht sein, bei mir geht alles.

**Comment by Der-WU** [comment]
Die Menü box für Umfragen funktioniert. Wenn ich aber auf Umfragen direkt gehe wird da keine angezeigt und im debug modus kommt der Fehler 2 von oben. 

Gruß WU

**Comment by hammermaps** [comment]
Umfragen Fix:
https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/6a5d0f03a352332c5aa7e732b1bfb86a94236113

**Comment by Der-WU** [comment]
Leider ist das Problem nicht behoben. :(

"WARNUNG: MySQL Query"
"Fail MySQL Query: SELECT \* FROM dzcp_votes AND forum = 0 ORDER BY intern DESC"
"WARNUNG:' /inc/database.php '"
"Line:"374" => mysqli_fetch_assoc(): Couldn't fetch mysqli_result"

Gruß WU

**Comment by hammermaps** [comment]
Erneuter versuch^^
https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/ec0fd07bb5a9a16071d7ea8a5577d2045f77408c

**Comment by Der-WU** [comment]
Super arbeit.
Jetzt läuft es auch mit älteren PHP Versionen. :)

Gruß WU
