### ISSUE TITLE
Reg. Fehler

### ISSUE THREAD

**Issue by Der-WU** [Hammermaps-DEV/DZCP-Extended-Edition#5]
Ich halte dich mal am arbeiten. *g

Mir ist gerade aufgefallen das die Regestrierung nicht funktioniert.
Weder bei mir noch bei dir. Es kommt nach dem Absenden immer:

Fatal error: Class 'Mailer' not found in /var/www/Privat/htdocs/2013/inc/common.php on line 1081 

Gruß WU

**Comment by hammermaps** [comment]
Wäre ja nicht so als wäre ich sofort arbeitslos^^

Scheind so als hätte ich meine baustelle hochgeladen xD
An der Mail-Function war ich am bauen und noch nicht fertig, ich lade gleich eine korektur hoch. 
Damit das überhaupt wieder geht^^

**Comment by hammermaps** [comment]
Der Commit: https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/commit/5fa7ac0a504d14fdb44f7f6019e51b46687b7812
Hier eine ZIP: https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/raw/master/_updates_zip_/DZCP-EE_0172_22_07_13.zip
Bitte die inc/sendmail.php löschen, die wird nicht mehr verwendet.

Sollte nun wieder gehen^^

Ps. 
Du solltest mal schauen ob du einen Memcache Server oder die PHP Erweiterung APC ans laufen bekommst, kannst DZCP darauf einstellen und gut Performance rausholen.
Ein schöner nebeneffect ist das deine SQL Datenbank entlastet wird.

**Comment by Der-WU** [comment]
Funktioniert. Mit dem cache lese ich mich mal ein. Werde es dann mal auf meinem Server installieren und in Verbindung mit dzcp testen. Aber habe noch nen kleines anliegen. Die download Zeitangaben funktionieren noch nicht. :)

Gruß WU

**Comment by hammermaps** [comment]
Schau ob da die Datengröße steht, die url in der administration macht immer bei der auswahl die domain dran.
http://127.0.0.1/C:/Users/masterbee/Zend/workspaces/DefaultWorkspace/DZCP-Extended Edition/inc/tinymce_files/mods.zip
zbs.
sollte aber nur C:/Users/masterbee/Zend/workspaces/DefaultWorkspace/DZCP-Extended Edition/inc/tinymce_files/mods.zip sein, 
wird bei Linux änlich aussehen, das muss ich noch fixen aber kommt erst wenn ich es überarbeite.

**Comment by Der-WU** [comment]
Dafür muss man ja den Kompletten Zend Server installieren. Oo
Gibt es nicht nen einfaches Zend Modul das man laden kann fürs Caching?
Never change a running system.
Zend will alles austauschen was mit php zu tun hat, ist mir zu Risikohaft das gleich Garnichts mehr geht. ;)

**Comment by hammermaps** [comment]
wo für sollst du den zend server installieren?
Ohne Zend Server kann man memcache,apc,file,mysql verwenden.
Muss man nur nach installieren und in php aktivieren.
Wenn du das meinst?

**Comment by Der-WU** [comment]
Für das caching via zend.
Hab jetzt memcache am laufen.

**Comment by hammermaps** [comment]
ja die ZEND Server - Disk Cache und die ZEND Server - Shared Memory Cache die laufen nur auf Zend Servern, sind aber nur eine Option, wer zend server hat kann die verwenden, die keinen zend server haben können memcache,file,apc,mysql verwenden.
Ist aber kein muss, darum habe ich da gute alternativen vorgesehen.
Also brauchst da keinen Zend Server Installieren außer du möchtest umbedingt etwas davon verwenden^^
wo der ZEND Server - Shared Memory Cache, Memcache und APC etwa die gleiche geschwindigkeit in DZCP erziehlen.
Also der Betrieb per Memcache passt genau so gut^^

Ps.
Wenn dich die Meldungen oben in der Debug Console stören kannst die php files für die 2 Cache typen auch löschen.

class_cache_zend_disk.php und class_cache_zend_shm.php
