### ISSUE TITLE
TS3 Viewer hilfe

### ISSUE THREAD

**Issue by Der-WU** [Hammermaps-DEV/DZCP-Extended-Edition#7]
Hey.

Seit gestern funzt bei mir der TS3 Viewer nicht mehr.
Einfach so von jetzt auf gleich.
Aber aus dem Fehler werde ich nicht schlau.
Fällt dir was dazu ein?

 Fatal error: Uncaught exception 'GameQ_ProtocolsException' with message 'GameQ_Protocols_Teamspeak3::verify_response: Header response was not ok. Response ' in /var/www/Privat/htdocs/inc/gameq/protocols/teamspeak3.php:367 Stack trace: #0 /var/www/Privat/htdocs/inc/gameq/protocols/teamspeak3.php(385): GameQ_Protocols_Teamspeak3->verify_response('') #1 /var/www/Privat/htdocs/inc/gameq/protocols/teamspeak3.php(178): GameQ_Protocols_Teamspeak3->parse_response(Object(GameQ_Buffer)) #2 [internal function]: GameQ_Protocols_Teamspeak3->process_details() #3 /var/www/Privat/htdocs/inc/gameq/protocols/core.php(556): call_user_func_array(Array, Array) #4 /var/www/Privat/htdocs/inc/gameq.php(332): GameQ_Protocols_Core->processResponse() #5 /var/www/Privat/htdocs/inc/gameq.php(310): GameQ::filterResponse(Object(GameQ_Protocols_Teamspeak3)) #6 /var/www/Privat/htdocs/teamspeak/pages/action_ajax.php(55): GameQ::requestData() #7 /var/www/Privat/htdocs/teamspeak/pages/action_ajax.php(107): teamspeak_show() #8 /var/www/Privat/htdocs/teamspe in /var/www/Privat/htdocs/inc/gameq/protocols/core.php on line 564 

Gruß WU

**Comment by hammermaps** [comment]
Es scheind sich irgentetwas zwischen dzcp und dem ts3 server geändert zu haben.
Normal fall gibt der ts3 server msg=ok zurück aber bei dir scheinbar nicht.
Wenn du nix geändert hast, wird das problem bein ts3 sein, ggf. wurde die ip des webservers gebannt.
Eigendlich wird ts3 viewer nur alle 30 sekunden aktualisiert, wenn das umgestellt wurde kann man schnell gebannt werden.

**Comment by Der-WU** [comment]
Theoretisch sollte sich nichts geändert haben.
Praktisch will ich nicht abstreiten das schon wieder jemand an den Srv Rechten rum gefummelt hat.

Nunja, dann werde ich wohl mal alle rechte durch gehen müssen.

Wie kann es sein das die Seiten Unterschiedliche Codierungen nutzen!?
z.B nutzt Kalender und TSviewer UTF-8 und News und Gästebuch ISO.
Was zu Anzeigefehlern führt bei Umlauten.

Gruß WU

**Comment by Der-WU** [comment]
```
channelgrouplist > List channel groups aka b_virtualserver_channelgroup_list
servergrouplist > List server groups aka b_virtualserver_servergroup_list
clientlist > List clients online on a virtual server aka b_virtualserver_client_list
channellist > List channels on a virtual server aka b_virtualserver_channel_list
version > Retrieve global server version aka b_serverinstance_version_view
serverinfo > Retrieve virtual server information aka b_virtualserver_info_view
clientinfo > Retrieve client information aka b_client_info_view
```

Sind die von GameQ benötigten rechte um korrekt zu funktionieren. :)

Gruß WU

**Comment by hammermaps** [comment]
Codierung ist mir bekannt da muss ich alle seiten auf utf8 umstellen da sonst TS3 und GameServern Probleme mit sonderzeichen haben, wenn ich alles auf UTF8 umstelle dann bekomme ich wieder Probleme mit den infoboxen die auf javaskript basieren.
Das ist ein bischen blöd und weis noch nicht wie ich das genau angehen soll.

Machst du eine Sache weg so das es geht, geht eine andere die vorher ging nicht mehr.^^
