### ISSUE TITLE
Admin Menu

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#8]
Erstmal hut ab das du dir soviel muehe gemacht hast das cms auszubessern. Finde es sehr gut das du dir die arbeit gemacht hast und die Hauptseiten unterteilt hast und die ganzen cases nach aussen gelagert hast.

Ich persoenlich finde die Ordner Struktur im Admin Bereich nicht so dolle. Es waere gut wenn man dort die cases auch auslagert macht das ganze system mehr durchsichtig fuer neulinge und evtl hilft es auch dort programier fehler abzufangen wenn man mal dort was zerstoert hat und kann evtl auch nur diese datei austauschen und nicht von vorne anfangen alles abzuaendern.

Wie du das ganze handhabst bleibt natuerlich dir ueberlassen werde mir mal in ruhe das cms angucken und evtl finde ich ja noch was was man haette anders machen koennen oder besser.

**Comment by hammermaps** [comment]
Danke,
Man könnte Ordner für jede menu anlegen, dort eine index + unterseiten anlegen.
Änlich wie mit den _Normalen Seiten_ News/Artikel usw.

**Comment by Aviator-Coding** [comment]
also ich wueder es so machen wuerde es von der mod seite her einfacher machen wueder da nen ordner mit config anlegen wo die xml dateien auslesen diesen ordner wuerde ich dann nehmen um z.b. die unterordner auslesen zu lassen. Z.b. 

admin
- config
   -ddd.xml
   -ddd.xml
  - icons 
  - [modul]
    - actions oder wie auch immer

denke mal das das schon ein wenig besser machen wuerde

**Comment by hammermaps** [comment]
Muss halt drauf achten das es meine mod api nicht zerhaut, die greift da auch rein.
Aber ansich würde ich das auch so machen wie du geschrieben hast.
Wo bei die jewaligen xml files im hauptordner verbleiben, da es sonst zu performance problemen kommen könnte auf grund der vielen zugriffe beim aufruf der administrations navigation.
