### ISSUE TITLE
Ordner Structur (Windows Systeme)

### ISSUE THREAD

**Issue by Aviator-Coding** [Hammermaps-DEV/DZCP-Extended-Edition#9]
Du hast ein paar ordner vergessen in deine Version einzufuegen.

![installer](https://f.cloud.github.com/assets/5182697/926035/f241bd42-ff83-11e2-8443-f24e9ebfeb0f.jpg)

**Comment by hammermaps** [comment]
Da war Github schuld, der erkennt keine leeren Ordner ich hab vor par Tagen dort null files reingepackt damit der die mit hochlät.
Wie es aussieht ist deine Kopie nicht mehr ganz aktuell, sehe:
https://github.com/Hammermaps-DEV/DZCP-Extended-Edition/tree/master/inc/images/uploads/useravatare
also müste der ordner auch im zip bzw. im replo. vorhanden sein.

**Comment by Aviator-Coding** [comment]
hab eben mal nen update gemacht von der repo. evtl sollte man den installer die ordner falls die nicht da sind erstellen lassen waere auch ne moeglichkeit um es perfekt zu haben

**Comment by hammermaps** [comment]
Ist gute Idee, werde ich als ToDo auf Github setzen.
Muss mir da noch gute umsetzung überlegen da PHP  nicht immer selber ohne nötige Rechte Ordner anlegen kann.
bzw. die nötigen schreibrechte besitzt bis der administrator/webmaster per ftp die rechte setzt.
